enabled: true
sidebarEnabled: active
dropdown:
  enabled: true
contact:
  statement: 'Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.'
  email: webmaster@example.com
  phone: '(555) 555-5555'
  street: '123 Any Street'
  city: AnyTown
  state: CA
  zip: '12345'
themeSlogan: 'Lab Report Help for U of R Biology Students'
social:
  twitter: 'https://twitter.com/UofRegina/'
  facebook: 'https://www.facebook.com/UniversityofRegina/'
  snap: null
  instagram: 'https://www.instagram.com/uofreginaofficial'
  medium: null
